"""empty message

Revision ID: 313b6299dac5
Revises: b10b044bba0c
Create Date: 2024-09-07 20:17:15.869241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b6299dac5'
down_revision = 'b10b044bba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
